### ISSUE TITLE
First PIMRequest work, but second does not

### ISSUE THREAD

**Issue by erkjo** [janegilring/PIMTools#1]
I think there is a bug in `New-AzurePIMRequest`. First request works fine. Second only returns `User user@xx.com` is already elevated`.

When I look into the code, I see that line 80 is querying existing role assignments, but the where clause does not filter for resource id.

` $ExistingRoleAssignmentRequest = AzureADPreview\Get-AzureADMSPrivilegedRoleAssignmentRequest -ProviderId azureResources | Where-Object RequestedDateTime -gt (Get-Date).AddHours(-8)`

**Comment by janegilring** [comment]
Good catch - will look into adding a filter for resource id. Thanks for reporting!

**Comment by janegilring** [comment]
Fixed by 20413d24e7eef01f9712d6fb375705433cf0951b

Updated module published to PS Gallery.
