### ISSUE TITLE
Improved handling of RoleName parameter in AzureAD

### ISSUE THREAD

**Issue by scottchamings** [janegilring/PIMTools#2]
This is my first contribution to a project, so let me know if I can do better....

Found that even if rolename parameter is specified, user is forced to click on output from out-gridview.

I have forked the code and added better handling so that out-gridview is only launched for when rolename is not specified.

Tested these changes locally.

Summary of changes in my forked code @https://github.com/scottchamings/PIMTools

Line 5 updated
from 

   `     $RoleName = 'Global Reader', '`
to

`        $RoleName = '',`

Updated Line 61
from 

`Default { $roleDefinition = AzureADPreview\Get-AzureADMSPrivilegedRoleDefinition -ProviderId aadRoles -ResourceId $AzureADCurrentSessionInfo.TenantId | Out-GridView -PassThru }`

to

`'' { $roleDefinition = AzureADPreview\Get-AzureADMSPrivilegedRoleDefinition -ProviderId aadRoles -ResourceId $AzureADCurrentSessionInfo.TenantId | Out-GridView -PassThru }`

Added new Line 62

` Default { $roleDefinition = AzureADPreview\Get-AzureADMSPrivilegedRoleDefinition -ProviderId aadRoles -ResourceId $AzureADCurrentSessionInfo.TenantId | Where-Object {$_.DisplayName -eq $RoleName} }`

**Comment by janegilring** [comment]
Thanks a lot @scottchamings - the changes looks great!

I've merged the PR and published the new version to the PS Gallery.

**Comment by scottchamings** [comment]
Not a problem and my first ever public pull request 8-)

**Comment by janegilring** [comment]
Awesome - now the snowball has started rolling 😃👌
