### ISSUE TITLE
PIM elevation fails due to policy breach

### ISSUE THREAD

**Issue by b7ruce** [janegilring/PIMTools#4]
PIM elevation fails because TicketingRule policy is breached.

![image](https://user-images.githubusercontent.com/47275509/111422851-a5173780-86ef-11eb-9ea0-213272cc84f6.png)

Our PIM requires the entry of a ticket number

![image](https://user-images.githubusercontent.com/47275509/111423157-27076080-86f0-11eb-988f-3b8fe0e1a65f.png)

Can you please extend the set of parameters so ticket system and ticket number can be optionally provided?

**Comment by b7ruce** [comment]
Just had to learn that this is by design not available yet. 

![image](https://user-images.githubusercontent.com/47275509/111424198-b3665300-86f1-11eb-9325-b67ea43d1228.png)

**Comment by janegilring** [comment]
Thanks for checking this - we can look at getting it implemented as soon as support for PowerShell is in place 👍
