### ISSUE TITLE
Get-AzureADMSPrivilegedResource bug

### ISSUE THREAD

**Issue by ghost** [janegilring/PIMTools#6]
Get-AzureADMSPrivilegedResource usage has a bug. There is a limitation of the number of resources that can be listed. If you have more selection will fail

Filter should look like this instead of searching by name afterwards

-Filter "Type eq 'resourcegroup' and DisplayName eq '$ResourceName'"

**Comment by janegilring** [comment]
Thanks for reporting, a new version is now published to the PowerShell Gallery.

https://github.com/janegilring/PIMTools/commit/352c19bebc5fee5a80486248f8d53cf2b6acba40
